[app]
name = "Homelab Management Panel"
footer = "Made by kulisak!"
panel_password = "$argon2id$v=19$m=65536,t=3,p=4$mWofgvDOKoNUtsRiMEFfCg$G4Gl+Zlc459NN3A846lbV4ubfOTZzr/bh4yUodTg+I8"
current_cookie = "$argon2id$v=19$m=65536,t=3,p=4$xdk6wc7Gs/L932b1CjGGNQ$qnZdpNEN7tHSLz4965+kkKfjTXBR+K8URx+rY6/JNhs"
setup = true

[gunicorn]
port = "8080"
host = "127.0.0.1"

[user]
pinned_services = [
    "display-manager.service",
    "dbus-org.bluez.service",
    "testservice.service",
]
